// See https://aka.ms/new-console-template for more information
using AdventOfCode;

// Actual result for advent of code 2021.
//Day1Logic.AnalyzeDay1(@"TestFiles\day1.txt");
//Day2Logic.AnalyzeDay2(@"TestFiles\day2.txt");
//Day3Logic.AnalyzeDay3(@"TestFiles\day3.txt");
//Day4Logic.AnalyzeDay4(@"TestFiles\day4.txt");
//Day5Logic.AnalyzeDay5(@"TestFiles\day5.txt");
//Day6Logic.AnalyzeDay6(@"TestFiles\day6.txt");
//Day7Logic.AnalyzeDay7(@"TestFiles\day7.txt");
//Day8Logic.AnalyzeDay9(@"TestFiles\day8.txt");
//Day9Logic.AnalyzeDay9(@"TestFiles\day9.txt");
//Day10Logic.AnalyzeDay10(@"TestFiles\day10.txt");
//Day11Logic.AnalyzeDay(@"TestFiles\day11.txt");
//Day12Logic.AnalyzeDay(@"TestFiles\day12.txt");
//Day13Logic.AnalyzeDay(@"TestFiles\day13.txt");
//Day14Logic.AnalyzeDay(@"TestFiles\day14.txt");
//Day15Logic.AnalyzeDay(@"TestFiles\day15.txt");
//Day16Logic.AnalyzeDay(@"TestFiles\day16.txt");
//Day17Logic.AnalyzeDay(@"TestFiles\day17.txt");
//Day18Logic.AnalyzeDay(@"TestFiles\day18.txt");
//Day19Logic.AnalyzeDay(@"TestFiles\day19.txt");
//Day20Logic.AnalyzeDay(@"TestFiles\day20.txt");
//Day21Logic.AnalyzeDay(@"TestFiles\day21.txt");
//Day22Logic.AnalyzeDay(@"TestFiles\day22.txt");
//Day23Logic.AnalyzeDay(@"TestFiles\day23.txt");
Day24Logic.AnalyzeDay(@"TestFiles\day24.txt");
//Day25Logic.AnalyzeDay(@"TestFiles\day25.txt");

// This is to assist me in testing the test data.
//Day1Logic.AnalyzeDay1(@"TestFiles\day1TestData.txt");
//Day2Logic.AnalyzeDay2(@"TestFiles\day2TestData.txt");
//Day3Logic.AnalyzeDay3(@"TestFiles\day3TestData.txt");
//Day4Logic.AnalyzeDay4(@"TestFiles\day4TestData.txt");
//Day5Logic.AnalyzeDay5(@"TestFiles\day5TestData.txt");
//Day6Logic.AnalyzeDay6(@"TestFiles\day6TestData.txt");
//Day7Logic.AnalyzeDay7(@"TestFiles\day7TestDataSimple.txt");
//Day7Logic.AnalyzeDay7(@"TestFiles\day7TestData.txt");
//Day8Logic.AnalyzeDay9(@"TestFiles\day8TestData.txt");
//Day9Logic.AnalyzeDay9(@"TestFiles\day9TestData.txt");
//Day10Logic.AnalyzeDay10(@"TestFiles\day10TestData.txt");
//Day11Logic.AnalyzeDay(@"TestFiles\day11TestData.txt");
//Day12Logic.AnalyzeDay(@"TestFiles\day12TestData.txt");
//Day12Logic.AnalyzeDay(@"TestFiles\day12TestData2.txt");
//Day12Logic.AnalyzeDay(@"TestFiles\day12TestData3.txt");
//Day13Logic.AnalyzeDay(@"TestFiles\day13TestData.txt");
//Day14Logic.AnalyzeDay(@"TestFiles\day14TestData.txt");
//Day15Logic.AnalyzeDay(@"TestFiles\day15TestData.txt");
//Day15Logic.AnalyzeDay(@"TestFiles\day15TestData2.txt");
//Day16Logic.AnalyzeDay(@"TestFiles\day16TestData.txt");
//Day16Logic.TestDayBWithSampleInput();
//Day17Logic.AnalyzeDay(@"TestFiles\day17TestData.txt");
//Day18Logic.AnalyzeDay(@"TestFiles\day18TestData.txt");
//Day19Logic.AnalyzeDay(@"TestFiles\day19TestData.txt");
//Day20Logic.AnalyzeDay(@"TestFiles\day20TestData.txt");
//Day21Logic.AnalyzeDay(@"TestFiles\day21TestData.txt");
//Day22Logic.AnalyzeDay(@"TestFiles\day22TestData.txt");
//Day23Logic.AnalyzeDay(@"TestFiles\day23TestData.txt");
//Day24Logic.AnalyzeDay(@"TestFiles\day24TestData.txt");
//Day25Logic.AnalyzeDay(@"TestFiles\day25TestData.txt");